//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Adapters
{
    
    public class IConfigurationEntryViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IConfigurationEntryContract
    {
        private Start9.Views.IConfigurationEntry _view;
        public IConfigurationEntryViewToContractAddInAdapter(Start9.Views.IConfigurationEntry view)
        {
            _view = view;
        }
        public object Object
        {
            get
            {
                return _view.Object;
            }
        }
        public string FriendlyName
        {
            get
            {
                return _view.FriendlyName;
            }
        }
        internal Start9.Views.IConfigurationEntry GetSourceView()
        {
            return _view;
        }
    }
}

