//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Adapters
{
    
    public class IConfigurationViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IConfigurationContract
    {
        private Start9.Views.IConfiguration _view;
        public IConfigurationViewToContractAddInAdapter(Start9.Views.IConfiguration view)
        {
            _view = view;
        }
        public System.AddIn.Contract.IListContract<Start9.Api.Contracts.IConfigurationEntryContract> Entries
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<Start9.Views.IConfigurationEntry, Start9.Api.Contracts.IConfigurationEntryContract>(_view.Entries, Start9.Adapters.IConfigurationEntryAddInAdapter.ViewToContractAdapter, Start9.Adapters.IConfigurationEntryAddInAdapter.ContractToViewAdapter);
            }
        }
        internal Start9.Views.IConfiguration GetSourceView()
        {
            return _view;
        }
    }
}

