//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    public class AConfigurationChangedEventArgsAddInAdapter
    {
        internal static Start9.Api.AConfigurationChangedEventArgs ContractToViewAdapter(Start9.Api.Contracts.IConfigurationChangedEventArgsContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(ConfigurationChangedEventArgsViewToContractAddInAdapter))))
            {
                return ((ConfigurationChangedEventArgsViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new ConfigurationChangedEventArgsContractToViewAddInAdapter(contract);
            }
        }
        internal static Start9.Api.Contracts.IConfigurationChangedEventArgsContract ViewToContractAdapter(Start9.Api.AConfigurationChangedEventArgs view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(ConfigurationChangedEventArgsContractToViewAddInAdapter)))
            {
                return ((ConfigurationChangedEventArgsContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new ConfigurationChangedEventArgsViewToContractAddInAdapter(view);
            }
        }
    }
}

