//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    public class IConfigurationEntryViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IConfigurationEntryContract
    {
        private Start9.Api.IConfigurationEntry _view;
        public IConfigurationEntryViewToContractAddInAdapter(Start9.Api.IConfigurationEntry view)
        {
            _view = view;
        }
        public object Object
        {
            get
            {
                return _view.Object;
            }
        }
        public System.Type Type
        {
            get
            {
                return _view.Type;
            }
        }
        internal Start9.Api.IConfigurationEntry GetSourceView()
        {
            return _view;
        }
    }
}

