//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    public class IConfigurationChangedEventHandlerContractToViewAddInAdapter
    {
        private Start9.Api.Contracts.IConfigurationChangedEventHandlerContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        public IConfigurationChangedEventHandlerContractToViewAddInAdapter(Start9.Api.Contracts.IConfigurationChangedEventHandlerContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public void Handler(object sender, Start9.Api.AConfigurationChangedEventArgs args)
        {
            _contract.Handler(Start9.Api.AddInSideAdapters.AConfigurationChangedEventArgsAddInAdapter.ViewToContractAdapter(args));
        }
        internal Start9.Api.Contracts.IConfigurationChangedEventHandlerContract GetSourceContract()
        {
            return _contract;
        }
    }
}

