//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    public class IConfigurationViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IConfigurationContract
    {
        private Start9.Api.IConfiguration _view;
        private System.Collections.Generic.Dictionary<Start9.Api.Contracts.IConfigurationChangedEventHandlerContract, System.EventHandler<Start9.Api.AConfigurationChangedEventArgs>> ConfigurationChanged_handlers;
        public IConfigurationViewToContractAddInAdapter(Start9.Api.IConfiguration view)
        {
            _view = view;
            ConfigurationChanged_handlers = new System.Collections.Generic.Dictionary<Start9.Api.Contracts.IConfigurationChangedEventHandlerContract, System.EventHandler<Start9.Api.AConfigurationChangedEventArgs>>();
        }
        public virtual void ConfigurationChangedEventAdd(Start9.Api.Contracts.IConfigurationChangedEventHandlerContract handler)
        {
            System.EventHandler<Start9.Api.AConfigurationChangedEventArgs> adaptedHandler = new System.EventHandler<Start9.Api.AConfigurationChangedEventArgs>(new Start9.Api.AddInSideAdapters.IConfigurationChangedEventHandlerContractToViewAddInAdapter(handler).Handler);
            _view.ConfigurationChanged += adaptedHandler;
            ConfigurationChanged_handlers[handler] = adaptedHandler;
        }
        public virtual void ConfigurationChangedEventRemove(Start9.Api.Contracts.IConfigurationChangedEventHandlerContract handler)
        {
            System.EventHandler<Start9.Api.AConfigurationChangedEventArgs> adaptedHandler;
            if (ConfigurationChanged_handlers.TryGetValue(handler, out adaptedHandler))
            {
                ConfigurationChanged_handlers.Remove(handler);
                _view.ConfigurationChanged -= adaptedHandler;
            }
        }
        internal Start9.Api.IConfiguration GetSourceView()
        {
            return _view;
        }
    }
}

