//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    public class IHostViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IHostContract
    {
        private Start9.Api.IHost _view;
        public IHostViewToContractAddInAdapter(Start9.Api.IHost view)
        {
            _view = view;
        }
        public virtual void PushMessage(Start9.Api.Contracts.IMessageContract message)
        {
            _view.PushMessage(Start9.Api.AddInSideAdapters.IMessageAddInAdapter.ContractToViewAdapter(message));
        }
        public virtual System.AddIn.Contract.IListContract<Start9.Api.Contracts.IConfigurationEntryContract> GetConfigurationEntries(Start9.Api.Contracts.IConfigurationContract configuration)
        {
            return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<Start9.Api.IConfigurationEntry, Start9.Api.Contracts.IConfigurationEntryContract>(_view.GetConfigurationEntries(Start9.Api.AddInSideAdapters.IConfigurationAddInAdapter.ContractToViewAdapter(configuration)), Start9.Api.AddInSideAdapters.IConfigurationEntryAddInAdapter.ViewToContractAdapter, Start9.Api.AddInSideAdapters.IConfigurationEntryAddInAdapter.ContractToViewAdapter);
        }
        public virtual Start9.Api.Contracts.IConfigurationContract GetGlobalConfiguration()
        {
            return Start9.Api.AddInSideAdapters.IConfigurationAddInAdapter.ViewToContractAdapter(_view.GetGlobalConfiguration());
        }
        public virtual System.AddIn.Contract.IListContract<Start9.Api.Contracts.IModuleContract> GetInstancesOfExecutingModule()
        {
            return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<Start9.Api.IModule, Start9.Api.Contracts.IModuleContract>(_view.GetInstancesOfExecutingModule(), Start9.Api.AddInSideAdapters.IModuleAddInAdapter.ViewToContractAdapter, Start9.Api.AddInSideAdapters.IModuleAddInAdapter.ContractToViewAdapter);
        }
        internal Start9.Api.IHost GetSourceView()
        {
            return _view;
        }
    }
}

