//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    public class IMessageEntryViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IMessageEntryContract
    {
        private Start9.Api.IMessageEntry _view;
        public IMessageEntryViewToContractAddInAdapter(Start9.Api.IMessageEntry view)
        {
            _view = view;
        }
        public System.Type Type
        {
            get
            {
                return _view.Type;
            }
        }
        public string DisplayName
        {
            get
            {
                return _view.DisplayName;
            }
        }
        internal Start9.Api.IMessageEntry GetSourceView()
        {
            return _view;
        }
    }
}

