//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    public class IMessageEntryContractToViewAddInAdapter : Start9.Api.IMessageEntry
    {
        private Start9.Api.Contracts.IMessageEntryContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IMessageEntryContractToViewAddInAdapter()
        {
        }
        public IMessageEntryContractToViewAddInAdapter(Start9.Api.Contracts.IMessageEntryContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public System.Type Type
        {
            get
            {
                return _contract.Type;
            }
        }
        public string DisplayName
        {
            get
            {
                return _contract.DisplayName;
            }
        }
        internal Start9.Api.Contracts.IMessageEntryContract GetSourceContract()
        {
            return _contract;
        }
    }
}

