//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    public class IMessageEntryAddInAdapter
    {
        internal static Start9.Api.IMessageEntry ContractToViewAdapter(Start9.Api.Contracts.IMessageEntryContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IMessageEntryViewToContractAddInAdapter))))
            {
                return ((IMessageEntryViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IMessageEntryContractToViewAddInAdapter(contract);
            }
        }
        internal static Start9.Api.Contracts.IMessageEntryContract ViewToContractAdapter(Start9.Api.IMessageEntry view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IMessageEntryContractToViewAddInAdapter)))
            {
                return ((IMessageEntryContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IMessageEntryViewToContractAddInAdapter(view);
            }
        }
    }
}

