//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    public class IModuleContractToViewAddInAdapter : Start9.Api.IModule
    {
        private Start9.Api.Contracts.IModuleContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IModuleContractToViewAddInAdapter()
        {
        }
        public IModuleContractToViewAddInAdapter(Start9.Api.Contracts.IModuleContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public Start9.Api.IConfiguration Configuration
        {
            get
            {
                return Start9.Api.AddInSideAdapters.IConfigurationAddInAdapter.ContractToViewAdapter(_contract.Configuration);
            }
        }
        public System.Collections.Generic.IList<Start9.Api.IMessageEntry> MessageContract
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIList<Start9.Api.Contracts.IMessageEntryContract, Start9.Api.IMessageEntry>(_contract.MessageContract, Start9.Api.AddInSideAdapters.IMessageEntryAddInAdapter.ContractToViewAdapter, Start9.Api.AddInSideAdapters.IMessageEntryAddInAdapter.ViewToContractAdapter);
            }
        }
        public System.Collections.Generic.IList<Start9.Api.IReceiverEntry> ReceiverContract
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIList<Start9.Api.Contracts.IReceiverEntryContract, Start9.Api.IReceiverEntry>(_contract.ReceiverContract, Start9.Api.AddInSideAdapters.IReceiverEntryAddInAdapter.ContractToViewAdapter, Start9.Api.AddInSideAdapters.IReceiverEntryAddInAdapter.ViewToContractAdapter);
            }
        }
        public void ShowConfigurator()
        {
            _contract.ShowConfigurator();
        }
        public void Initialize(Start9.Api.IHost host, Start9.Api.IConfiguration loadedConfig)
        {
            _contract.Initialize(Start9.Api.AddInSideAdapters.IHostAddInAdapter.ViewToContractAdapter(host), Start9.Api.AddInSideAdapters.IConfigurationAddInAdapter.ViewToContractAdapter(loadedConfig));
        }
        internal Start9.Api.Contracts.IModuleContract GetSourceContract()
        {
            return _contract;
        }
    }
}

