//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    [System.AddIn.Pipeline.AddInAdapterAttribute()]
    public class IModuleViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IModuleContract
    {
        private Start9.Api.IModule _view;
        public IModuleViewToContractAddInAdapter(Start9.Api.IModule view)
        {
            _view = view;
        }
        public Start9.Api.Contracts.IConfigurationContract Configuration
        {
            get
            {
                return Start9.Api.AddInSideAdapters.IConfigurationAddInAdapter.ViewToContractAdapter(_view.Configuration);
            }
        }
        public System.AddIn.Contract.IListContract<Start9.Api.Contracts.IMessageEntryContract> MessageContract
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<Start9.Api.IMessageEntry, Start9.Api.Contracts.IMessageEntryContract>(_view.MessageContract, Start9.Api.AddInSideAdapters.IMessageEntryAddInAdapter.ViewToContractAdapter, Start9.Api.AddInSideAdapters.IMessageEntryAddInAdapter.ContractToViewAdapter);
            }
        }
        public System.AddIn.Contract.IListContract<Start9.Api.Contracts.IReceiverEntryContract> ReceiverContract
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<Start9.Api.IReceiverEntry, Start9.Api.Contracts.IReceiverEntryContract>(_view.ReceiverContract, Start9.Api.AddInSideAdapters.IReceiverEntryAddInAdapter.ViewToContractAdapter, Start9.Api.AddInSideAdapters.IReceiverEntryAddInAdapter.ContractToViewAdapter);
            }
        }
        public virtual void ShowConfigurator()
        {
            _view.ShowConfigurator();
        }
        public virtual void Initialize(Start9.Api.Contracts.IHostContract host, Start9.Api.Contracts.IConfigurationContract loadedConfig)
        {
            _view.Initialize(Start9.Api.AddInSideAdapters.IHostAddInAdapter.ContractToViewAdapter(host), Start9.Api.AddInSideAdapters.IConfigurationAddInAdapter.ContractToViewAdapter(loadedConfig));
        }
        internal Start9.Api.IModule GetSourceView()
        {
            return _view;
        }
    }
}

