//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    public class IReceiverEntryAddInAdapter
    {
        internal static Start9.Api.IReceiverEntry ContractToViewAdapter(Start9.Api.Contracts.IReceiverEntryContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IReceiverEntryViewToContractAddInAdapter))))
            {
                return ((IReceiverEntryViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IReceiverEntryContractToViewAddInAdapter(contract);
            }
        }
        internal static Start9.Api.Contracts.IReceiverEntryContract ViewToContractAdapter(Start9.Api.IReceiverEntry view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IReceiverEntryContractToViewAddInAdapter)))
            {
                return ((IReceiverEntryContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IReceiverEntryViewToContractAddInAdapter(view);
            }
        }
    }
}

