//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Api.AddInSideAdapters
{
    
    public class IReceiverEntryContractToViewAddInAdapter : Start9.Api.IReceiverEntry
    {
        private Start9.Api.Contracts.IReceiverEntryContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IReceiverEntryContractToViewAddInAdapter()
        {
        }
        public IReceiverEntryContractToViewAddInAdapter(Start9.Api.Contracts.IReceiverEntryContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public System.Type Type
        {
            get
            {
                return _contract.Type;
            }
        }
        public string DisplayName
        {
            get
            {
                return _contract.DisplayName;
            }
        }
        public void SendMessage(IMessage message)
        {
            _contract.SendMessage(IMessageAddInAdapter.ViewToContractAdapter(message));
        }

        internal Start9.Api.Contracts.IReceiverEntryContract GetSourceContract()
        {
            return _contract;
        }
    }
}

